import {
  AdminCreateFulfillmentSet,
  AdminCreateGeoZone,
  AdminCreateServiceZone,
  AdminUpdateFulfillmentSet,
  AdminUpdateServiceZone,
  AdminZoneIdParams,
  IdParams,
} from '@proteus/http-schemas'
import type { MiddlewareRoute } from '../../../core/middleware/types.js'
import { Tags } from '../../../core/middleware/types.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets',
    operationId: 'listAdminFulfillmentSets',
    summary: 'List fulfillment sets',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets',
    bodySchema: AdminCreateFulfillmentSet,
    operationId: 'createAdminFulfillmentSet',
    summary: 'Create a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    operationId: 'getAdminFulfillmentSet',
    summary: 'Retrieve a fulfillment set with service zones',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    bodySchema: AdminUpdateFulfillmentSet,
    operationId: 'updateAdminFulfillmentSet',
    summary: 'Update a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    operationId: 'deleteAdminFulfillmentSet',
    summary: 'Delete a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones',
    paramsSchema: IdParams,
    bodySchema: AdminCreateServiceZone,
    operationId: 'createAdminServiceZone',
    summary: 'Create a service zone in a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: AdminZoneIdParams,
    operationId: 'getAdminServiceZone',
    summary: 'Retrieve a service zone with geo zones',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: AdminZoneIdParams,
    bodySchema: AdminUpdateServiceZone,
    operationId: 'updateAdminServiceZone',
    summary: 'Update a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: AdminZoneIdParams,
    operationId: 'deleteAdminServiceZone',
    summary: 'Delete a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId/geo-zones',
    paramsSchema: AdminZoneIdParams,
    bodySchema: AdminCreateGeoZone,
    operationId: 'createAdminGeoZone',
    summary: 'Add a geo zone to a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
] satisfies MiddlewareRoute[]
