import {
  CreateFulfillmentSet,
  CreateGeoZone,
  CreateServiceZone,
  IdParams,
  UpdateFulfillmentSet,
  UpdateServiceZone,
  ZoneIdParams,
} from '@proteus/http-schemas'
import type { MiddlewareRoute } from '../../../core/middleware/types.js'
import { Tags } from '../../../core/middleware/types.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets',
    operationId: 'listAdminFulfillmentSets',
    summary: 'List fulfillment sets',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets',
    bodySchema: CreateFulfillmentSet,
    operationId: 'createAdminFulfillmentSet',
    summary: 'Create a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    operationId: 'getAdminFulfillmentSet',
    summary: 'Retrieve a fulfillment set with service zones',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    bodySchema: UpdateFulfillmentSet,
    operationId: 'updateAdminFulfillmentSet',
    summary: 'Update a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id',
    paramsSchema: IdParams,
    operationId: 'deleteAdminFulfillmentSet',
    summary: 'Delete a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones',
    paramsSchema: IdParams,
    bodySchema: CreateServiceZone,
    operationId: 'createAdminServiceZone',
    summary: 'Create a service zone in a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: ZoneIdParams,
    operationId: 'getAdminServiceZone',
    summary: 'Retrieve a service zone with geo zones',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: ZoneIdParams,
    bodySchema: UpdateServiceZone,
    operationId: 'updateAdminServiceZone',
    summary: 'Update a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    paramsSchema: ZoneIdParams,
    operationId: 'deleteAdminServiceZone',
    summary: 'Delete a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId/geo-zones',
    paramsSchema: ZoneIdParams,
    bodySchema: CreateGeoZone,
    operationId: 'createAdminGeoZone',
    summary: 'Add a geo zone to a service zone',
    tags: [Tags.FULFILLMENT_SETS],
  },
] satisfies MiddlewareRoute[]
