/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedShellRouteRouteImport } from './routes/_authed/_shell/route'
import { Route as AuthedShellIndexRouteImport } from './routes/_authed/_shell/index'
import { Route as AuthedSettingsStoreRouteImport } from './routes/_authed/settings/store'
import { Route as AuthedShellCustomersRouteImport } from './routes/_authed/_shell/customers'
import { Route as AuthedShellProductsRouteRouteImport } from './routes/_authed/_shell/products/route'
import { Route as AuthedShellProductsIndexRouteImport } from './routes/_authed/_shell/products/index'
import { Route as AuthedShellProductsCreateRouteImport } from './routes/_authed/_shell/products/create'
import { Route as AuthedShellProductsIdRouteRouteImport } from './routes/_authed/_shell/products/$id/route'
import { Route as AuthedShellProductsIdEditRouteImport } from './routes/_authed/_shell/products/$id/edit'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedShellRouteRoute = AuthedShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedShellIndexRoute = AuthedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedShellRouteRoute,
} as any)
const AuthedSettingsStoreRoute = AuthedSettingsStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedShellCustomersRoute = AuthedShellCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedShellRouteRoute,
} as any)
const AuthedShellProductsRouteRoute =
  AuthedShellProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthedShellRouteRoute,
  } as any)
const AuthedShellProductsIndexRoute =
  AuthedShellProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedShellProductsCreateRoute =
  AuthedShellProductsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedShellProductsIdRouteRoute =
  AuthedShellProductsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedShellProductsIdEditRoute =
  AuthedShellProductsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedShellProductsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedShellIndexRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/products': typeof AuthedShellProductsRouteRouteWithChildren
  '/customers': typeof AuthedShellCustomersRoute
  '/settings/store': typeof AuthedSettingsStoreRoute
  '/products/$id': typeof AuthedShellProductsIdRouteRouteWithChildren
  '/products/create': typeof AuthedShellProductsCreateRoute
  '/products/': typeof AuthedShellProductsIndexRoute
  '/products/$id/edit': typeof AuthedShellProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedShellIndexRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/customers': typeof AuthedShellCustomersRoute
  '/settings/store': typeof AuthedSettingsStoreRoute
  '/products/$id': typeof AuthedShellProductsIdRouteRouteWithChildren
  '/products/create': typeof AuthedShellProductsCreateRoute
  '/products': typeof AuthedShellProductsIndexRoute
  '/products/$id/edit': typeof AuthedShellProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/_shell': typeof AuthedShellRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_authed/_shell/products': typeof AuthedShellProductsRouteRouteWithChildren
  '/_authed/_shell/customers': typeof AuthedShellCustomersRoute
  '/_authed/settings/store': typeof AuthedSettingsStoreRoute
  '/_authed/_shell/': typeof AuthedShellIndexRoute
  '/_authed/_shell/products/$id': typeof AuthedShellProductsIdRouteRouteWithChildren
  '/_authed/_shell/products/create': typeof AuthedShellProductsCreateRoute
  '/_authed/_shell/products/': typeof AuthedShellProductsIndexRoute
  '/_authed/_shell/products/$id/edit': typeof AuthedShellProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/products'
    | '/customers'
    | '/settings/store'
    | '/products/$id'
    | '/products/create'
    | '/products/'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/login'
    | '/customers'
    | '/settings/store'
    | '/products/$id'
    | '/products/create'
    | '/products'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/_shell'
    | '/_authed/settings'
    | '/_public/login'
    | '/_authed/_shell/products'
    | '/_authed/_shell/customers'
    | '/_authed/settings/store'
    | '/_authed/_shell/'
    | '/_authed/_shell/products/$id'
    | '/_authed/_shell/products/create'
    | '/_authed/_shell/products/'
    | '/_authed/_shell/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_shell': {
      id: '/_authed/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_shell/': {
      id: '/_authed/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellIndexRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/settings/store': {
      id: '/_authed/settings/store'
      path: '/store'
      fullPath: '/settings/store'
      preLoaderRoute: typeof AuthedSettingsStoreRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_shell/customers': {
      id: '/_authed/_shell/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedShellCustomersRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/products': {
      id: '/_authed/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedShellProductsRouteRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/products/': {
      id: '/_authed/_shell/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedShellProductsIndexRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/_shell/products/create': {
      id: '/_authed/_shell/products/create'
      path: '/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthedShellProductsCreateRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/_shell/products/$id': {
      id: '/_authed/_shell/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedShellProductsIdRouteRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/_shell/products/$id/edit': {
      id: '/_authed/_shell/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthedShellProductsIdEditRouteImport
      parentRoute: typeof AuthedShellProductsIdRouteRoute
    }
  }
}

interface AuthedShellProductsIdRouteRouteChildren {
  AuthedShellProductsIdEditRoute: typeof AuthedShellProductsIdEditRoute
}

const AuthedShellProductsIdRouteRouteChildren: AuthedShellProductsIdRouteRouteChildren =
  {
    AuthedShellProductsIdEditRoute: AuthedShellProductsIdEditRoute,
  }

const AuthedShellProductsIdRouteRouteWithChildren =
  AuthedShellProductsIdRouteRoute._addFileChildren(
    AuthedShellProductsIdRouteRouteChildren,
  )

interface AuthedShellProductsRouteRouteChildren {
  AuthedShellProductsIdRouteRoute: typeof AuthedShellProductsIdRouteRouteWithChildren
  AuthedShellProductsCreateRoute: typeof AuthedShellProductsCreateRoute
  AuthedShellProductsIndexRoute: typeof AuthedShellProductsIndexRoute
}

const AuthedShellProductsRouteRouteChildren: AuthedShellProductsRouteRouteChildren =
  {
    AuthedShellProductsIdRouteRoute:
      AuthedShellProductsIdRouteRouteWithChildren,
    AuthedShellProductsCreateRoute: AuthedShellProductsCreateRoute,
    AuthedShellProductsIndexRoute: AuthedShellProductsIndexRoute,
  }

const AuthedShellProductsRouteRouteWithChildren =
  AuthedShellProductsRouteRoute._addFileChildren(
    AuthedShellProductsRouteRouteChildren,
  )

interface AuthedShellRouteRouteChildren {
  AuthedShellProductsRouteRoute: typeof AuthedShellProductsRouteRouteWithChildren
  AuthedShellCustomersRoute: typeof AuthedShellCustomersRoute
  AuthedShellIndexRoute: typeof AuthedShellIndexRoute
}

const AuthedShellRouteRouteChildren: AuthedShellRouteRouteChildren = {
  AuthedShellProductsRouteRoute: AuthedShellProductsRouteRouteWithChildren,
  AuthedShellCustomersRoute: AuthedShellCustomersRoute,
  AuthedShellIndexRoute: AuthedShellIndexRoute,
}

const AuthedShellRouteRouteWithChildren =
  AuthedShellRouteRoute._addFileChildren(AuthedShellRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsStoreRoute: typeof AuthedSettingsStoreRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsStoreRoute: AuthedSettingsStoreRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedShellRouteRoute: typeof AuthedShellRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedShellRouteRoute: AuthedShellRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
