import {
  AddCartShippingMethod,
  AddLineItem,
  CreateCart,
  DeleteResponse,
  IdParams,
  LineIdParams,
  StoreCartDetailResponse,
  StoreCartResponse,
  StoreCreateCartLineItemResponse,
  StoreCreateCartResponse,
  StoreCreateCartShippingMethodResponse,
  StoreShippingOptionListResponse,
  StoreUpdateCartLineItemResponse,
  StoreUpdateCartResponse,
  UpdateCart,
  UpdateLineItem,
} from '@proteus/http-schemas/store'
import type { MiddlewareRoute } from '../../../core/middleware/types.js'
import { Tags } from '../../../core/middleware/types.js'

export default [
  {
    method: 'POST',
    matcher: '/store/carts',
    bodySchema: CreateCart,
    operationId: 'createStoreCart',
    summary: 'Create a cart',
    tags: [Tags.CARTS],
    responseSchema: StoreCreateCartResponse,
  },
  {
    method: 'GET',
    matcher: '/store/carts/:id',
    paramsSchema: IdParams,
    operationId: 'getStoreCart',
    summary: 'Retrieve a cart with line items',
    tags: [Tags.CARTS],
    responseSchema: StoreCartDetailResponse,
  },
  {
    method: 'POST',
    matcher: '/store/carts/:id',
    paramsSchema: IdParams,
    bodySchema: UpdateCart,
    operationId: 'updateStoreCart',
    summary: 'Update a cart',
    tags: [Tags.CARTS],
    responseSchema: StoreUpdateCartResponse,
  },
  {
    method: 'POST',
    matcher: '/store/carts/:id/line-items',
    paramsSchema: IdParams,
    bodySchema: AddLineItem,
    operationId: 'addStoreCartLineItem',
    summary: 'Add a line item to a cart',
    tags: [Tags.CARTS],
    responseSchema: StoreCreateCartLineItemResponse,
  },
  {
    method: 'POST',
    matcher: '/store/carts/:id/line-items/:lineId',
    paramsSchema: LineIdParams,
    bodySchema: UpdateLineItem,
    operationId: 'updateStoreCartLineItem',
    summary: 'Update a cart line item',
    tags: [Tags.CARTS],
    responseSchema: StoreUpdateCartLineItemResponse,
  },
  {
    method: 'DELETE',
    matcher: '/store/carts/:id/line-items/:lineId',
    paramsSchema: LineIdParams,
    operationId: 'deleteStoreCartLineItem',
    summary: 'Remove a line item from a cart',
    tags: [Tags.CARTS],
    responseSchema: DeleteResponse,
  },
  {
    method: 'GET',
    matcher: '/store/carts/:id/shipping-options',
    paramsSchema: IdParams,
    operationId: 'listStoreCartShippingOptions',
    summary: 'List available shipping options for a cart',
    tags: [Tags.CARTS],
    responseSchema: StoreShippingOptionListResponse,
  },
  {
    method: 'POST',
    matcher: '/store/carts/:id/shipping-methods',
    paramsSchema: IdParams,
    bodySchema: AddCartShippingMethod,
    operationId: 'addStoreCartShippingMethod',
    summary: 'Select a shipping method for a cart',
    tags: [Tags.CARTS],
    responseSchema: StoreCreateCartShippingMethodResponse,
  },
  {
    method: 'POST',
    matcher: '/store/carts/:id/complete',
    paramsSchema: IdParams,
    operationId: 'completeStoreCart',
    summary: 'Complete a cart (authorize payment and mark as completed)',
    tags: [Tags.CARTS],
    responseSchema: StoreCartResponse,
  },
] satisfies MiddlewareRoute[]
