import {
  AdminCreateProduct,
  AdminCreateProductResponse,
  AdminCreateProductVariant,
  AdminCreateProductVariantResponse,
  AdminProductListParams,
  AdminProductListResponse,
  AdminProductResponse,
  AdminProductVariantListParams,
  AdminProductVariantListResponse,
  AdminProductVariantResponse,
  AdminUpdateProduct,
  AdminUpdateProductResponse,
  AdminUpdateProductVariant,
  AdminUpdateProductVariantResponse,
  DeleteResponse,
  IdParams,
  VariantIdParams,
} from '@proteus/http-schemas/admin'
import type { MiddlewareRoute } from '../../../core/middleware/types.js'
import { searchable, Tags } from '../../../core/middleware/types.js'
import type { ProductDTO, ProductVariantDTO } from '../../../core/types/product/common.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/products',
    querySchema: AdminProductListParams,
    searchableColumns: searchable<ProductDTO>('title', 'handle'),
    operationId: 'listProducts',
    summary: 'List products',
    tags: [Tags.PRODUCTS],
    responseSchema: AdminProductListResponse,
  },
  {
    method: 'POST',
    matcher: '/admin/products',
    bodySchema: AdminCreateProduct,
    operationId: 'createProduct',
    summary: 'Create a product',
    tags: [Tags.PRODUCTS],
    responseSchema: AdminCreateProductResponse,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id',
    paramsSchema: IdParams,
    operationId: 'getProduct',
    summary: 'Retrieve a product',
    tags: [Tags.PRODUCTS],
    responseSchema: AdminProductResponse,
  },
  {
    method: 'PATCH',
    matcher: '/admin/products/:id',
    paramsSchema: IdParams,
    bodySchema: AdminUpdateProduct,
    operationId: 'updateProduct',
    summary: 'Update a product',
    tags: [Tags.PRODUCTS],
    responseSchema: AdminUpdateProductResponse,
  },
  {
    method: 'DELETE',
    matcher: '/admin/products/:id',
    paramsSchema: IdParams,
    operationId: 'deleteProduct',
    summary: 'Delete a product',
    tags: [Tags.PRODUCTS],
    responseSchema: DeleteResponse,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id/variants',
    paramsSchema: IdParams,
    querySchema: AdminProductVariantListParams,
    searchableColumns: searchable<ProductVariantDTO>('title', 'sku'),
    operationId: 'listProductVariants',
    summary: 'List product variants',
    tags: [Tags.PRODUCT_VARIANTS],
    responseSchema: AdminProductVariantListResponse,
  },
  {
    method: 'POST',
    matcher: '/admin/products/:id/variants',
    paramsSchema: IdParams,
    bodySchema: AdminCreateProductVariant,
    operationId: 'createProductVariant',
    summary: 'Create a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    responseSchema: AdminCreateProductVariantResponse,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id/variants/:variantId',
    paramsSchema: VariantIdParams,
    operationId: 'getProductVariant',
    summary: 'Retrieve a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    responseSchema: AdminProductVariantResponse,
  },
  {
    method: 'PATCH',
    matcher: '/admin/products/:id/variants/:variantId',
    paramsSchema: VariantIdParams,
    bodySchema: AdminUpdateProductVariant,
    operationId: 'updateProductVariant',
    summary: 'Update a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    responseSchema: AdminUpdateProductVariantResponse,
  },
  {
    method: 'DELETE',
    matcher: '/admin/products/:id/variants/:variantId',
    paramsSchema: VariantIdParams,
    operationId: 'deleteProductVariant',
    summary: 'Delete a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    responseSchema: DeleteResponse,
  },
] satisfies MiddlewareRoute[]
