export { apiCall } from '../server/api-caller.js'
export * as customerByIdApi from './customers/[id]/route.js'
export * as customersApi from './customers/route.js'
export * as userByIdApi from './users/[id]/route.js'
export * as usersApi from './users/route.js'
