import { authenticate } from '@core/auth/middleware/authenticate.js'
import { validateScopeProviderAssociation } from '@core/auth/utils/validate-scope-provider-association.js'
import { validateToken } from '@core/auth/utils/validate-token.js'
import {
  AuthBody,
  AuthenticateResponse,
  AuthParams,
  AuthTokenResponse,
  ResetPasswordBody,
  ResetPasswordResponse,
  UpdatePasswordBody,
  UpdatePasswordResponse,
  VerificationConfirmBody,
  VerificationConfirmResponse,
  VerificationRequestBody,
  VerificationRequestResponse,
} from '@proteus/http-schemas/auth'
import type { MiddlewareRoute } from '../../core/middleware/types.js'
import { Tags } from '../../core/middleware/types.js'

export default [
  {
    method: 'POST',
    matcher: '/auth/:actorType/:authProvider/register',
    middlewares: [validateScopeProviderAssociation()],
    paramsSchema: AuthParams,
    bodySchema: AuthBody,
    operationId: 'authRegister',
    summary: 'Register with an auth provider',
    tags: [Tags.AUTH],
    responseSchema: AuthTokenResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/:actorType/:authProvider',
    middlewares: [validateScopeProviderAssociation()],
    paramsSchema: AuthParams,
    bodySchema: AuthBody,
    operationId: 'authAuthenticate',
    summary: 'Authenticate with an auth provider',
    tags: [Tags.AUTH],
    responseSchema: AuthenticateResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/:actorType/:authProvider/reset-password',
    middlewares: [validateScopeProviderAssociation()],
    paramsSchema: AuthParams,
    bodySchema: ResetPasswordBody,
    operationId: 'authResetPassword',
    summary: 'Request a password reset token',
    tags: [Tags.AUTH],
    responseSchema: ResetPasswordResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/:actorType/:authProvider/update',
    middlewares: [validateToken()],
    paramsSchema: AuthParams,
    bodySchema: UpdatePasswordBody,
    operationId: 'authUpdatePassword',
    summary: 'Update password using a reset token',
    tags: [Tags.AUTH],
    responseSchema: UpdatePasswordResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/token/refresh',
    middlewares: [authenticate('*', { allowUnregistered: true })],
    operationId: 'authTokenRefresh',
    summary: 'Refresh an auth token',
    tags: [Tags.AUTH],
    responseSchema: AuthenticateResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/verification/request',
    middlewares: [authenticate('*', { allowUnregistered: true })],
    bodySchema: VerificationRequestBody,
    operationId: 'authVerificationRequest',
    summary: 'Request a verification code',
    tags: [Tags.AUTH],
    responseSchema: VerificationRequestResponse,
  },
  {
    method: 'POST',
    matcher: '/auth/verification/confirm',
    middlewares: [authenticate('*', { allowUnregistered: true })],
    bodySchema: VerificationConfirmBody,
    operationId: 'authVerificationConfirm',
    summary: 'Confirm a verification code',
    tags: [Tags.AUTH],
    responseSchema: VerificationConfirmResponse,
  },
] satisfies MiddlewareRoute[]
